export default {
  HOME: "Home",
  LOGIN: "Login",
  SIGN_UP: "Sign Up",
  EXPLORE: "Explore",
  COMMUNITY: "Community",
  WALLET: "Your Wallet",
  PROFILE: "Your Profile",
  SCAN_CODE: "Scan Code",
  ACTIVE_TASK: "Active Task",
  SHARE_JOURNEY: "Share Journey",
  ACHIEVEMENTS: "Achievements",
  REWARDS: "Rewards",
  YOUR_POSTS: "Your Posts",
  AWARDED_POSTS: "Awarded Posts",
  LIKED_POSTS: "Liked Posts",
};
