import TimeOfDay from "./timeOfDay";

const tasks = [
  {
    id: 1,
    timeOfDay: TimeOfDay.MORNING,
    title: "Sunrise Stroll",
    description:
      "Start your day with a calm 1600-meter walk to greet the sunrise.",
    emoji: "🌅",
    timeStart: new Date().setHours(5, 0, 0, 0),
    timeEnd: new Date().setHours(8, 0, 0, 0),
    type: "distance-based",
    progress: 0,
    maxValue: 1600,
    completedAt: null,
  },
  {
    id: 2,
    timeOfDay: TimeOfDay.MORNING,
    title: "Step Fresh",
    description: "Aim for 3,000 steps to energize your morning routine.",
    emoji: "👟",
    timeStart: new Date().setHours(6, 0, 0, 0),
    timeEnd: new Date().setHours(9, 0, 0, 0),
    type: "step-based",
    progress: 0,
    maxValue: 3000,
    completedAt: null,
  },
  {
    id: 3,
    timeOfDay: TimeOfDay.MORNING,
    title: "Park Explorer",
    description:
      "Explore a nearby park for 30 minutes, discovering a new route each time.",
    emoji: "🌳",
    timeStart: new Date().setHours(7, 0, 0, 0),
    timeEnd: new Date().setHours(10, 0, 0, 0),
    type: "time-based",
    progress: 1800,
    maxValue: 1800,
    completedAt: new Date().setHours(7, 30, 0, 0),
  },
  {
    id: 4,
    timeOfDay: TimeOfDay.MORNING,
    title: "Morning Challenge",
    description: "Push for a quick 3200-meter walk to boost your metabolism.",
    emoji: "🏃",
    timeStart: new Date().setHours(6, 0, 0, 0),
    timeEnd: new Date().setHours(11, 0, 0, 0),
    type: "distance-based",
    progress: 0,
    maxValue: 3200,
    completedAt: null,
  },
  {
    id: 5,
    timeOfDay: TimeOfDay.MORNING,
    title: "Quiet Time Walk",
    description: "Take a 15-minute walk in silence, practicing mindfulness.",
    emoji: "🧘",
    timeStart: new Date().setHours(5, 0, 0, 0),
    timeEnd: new Date().setHours(8, 0, 0, 0),
    type: "time-based",
    progress: 900,
    maxValue: 900,
    completedAt: new Date().setHours(5, 15, 0, 0),
  },

  {
    id: 6,
    timeOfDay: TimeOfDay.AFTERNOON,
    title: "Lunch Loop",
    description: "A brisk 2400-meter walk post-lunch to aid digestion.",
    emoji: "🍽️",
    timeStart: new Date().setHours(11, 0, 0, 0),
    timeEnd: new Date().setHours(14, 0, 0, 0),
    type: "distance-based",
    progress: 0,
    maxValue: 2400,
    completedAt: null,
  },
  {
    id: 7,
    timeOfDay: TimeOfDay.AFTERNOON,
    title: "Step It Up",
    description:
      "Accumulate an additional 2,500 steps in your afternoon activities.",
    emoji: "👣",
    timeStart: new Date().setHours(12, 0, 0, 0),
    timeEnd: new Date().setHours(17, 0, 0, 0),
    type: "step-based",
    progress: 0,
    maxValue: 2500,
    completedAt: null,
  },
  {
    id: 8,
    timeOfDay: TimeOfDay.AFTERNOON,
    title: "Nature's Midday",
    description:
      "Spend 20 minutes walking in a natural setting, appreciating the daylight.",
    emoji: "🌞",
    timeStart: new Date().setHours(11, 0, 0, 0),
    timeEnd: new Date().setHours(15, 0, 0, 0),
    type: "time-based",
    progress: 1200,
    maxValue: 1200,
    completedAt: new Date().setHours(11, 20, 0, 0),
  },
  {
    id: 9,
    timeOfDay: TimeOfDay.AFTERNOON,
    title: "Urban Explorer",
    description:
      "Discover a new neighborhood or area in your city with a 3200-meter walk.",
    emoji: "🏙️",
    timeStart: new Date().setHours(12, 0, 0, 0),
    timeEnd: new Date().setHours(17, 0, 0, 0),
    type: "distance-based",
    progress: 3200,
    maxValue: 3200,
    completedAt: new Date().setHours(16, 0, 0, 0),
  },
  {
    id: 10,
    timeOfDay: TimeOfDay.AFTERNOON,
    title: "Afternoon Reset",
    description:
      "A 10-minute walk to clear your mind and refocus for the rest of the day.",
    emoji: "🔄",
    timeStart: new Date().setHours(13, 0, 0, 0),
    timeEnd: new Date().setHours(16, 0, 0, 0),
    type: "time-based",
    progress: 0,
    maxValue: 600,
    completedAt: null,
  },

  {
    id: 11,
    timeOfDay: TimeOfDay.EVENING,
    title: "Sunset Wind Down",
    description: "A relaxing 1600-meter walk to wind down as the sun sets.",
    emoji: "🌇",
    timeStart: new Date().setHours(17, 0, 0, 0),
    timeEnd: new Date().setHours(20, 0, 0, 0),
    type: "distance-based",
    progress: 0,
    maxValue: 1600,
    completedAt: null,
  },
  {
    id: 12,
    timeOfDay: TimeOfDay.EVENING,
    title: "Evening Steps",
    description: "Gather the last 2,000 steps to meet your daily goal.",
    emoji: "🎯",
    timeStart: new Date().setHours(18, 0, 0, 0),
    timeEnd: new Date().setHours(21, 0, 0, 0),
    type: "step-based",
    progress: 2000,
    maxValue: 2000,
    completedAt: new Date().setHours(20, 0, 0, 0),
  },
  {
    id: 13,
    timeOfDay: TimeOfDay.EVENING,
    title: "Night Sky Gazer",
    description:
      "15-minute walk under the night sky, stargazing and decompressing.",
    emoji: "🌌",
    timeStart: new Date().setHours(19, 0, 0, 0),
    timeEnd: new Date().setHours(22, 0, 0, 0),
    type: "time-based",
    progress: 0,
    maxValue: 900,
    completedAt: null,
  },
  {
    id: 14,
    timeOfDay: TimeOfDay.EVENING,
    title: "Reflective Walk",
    description:
      "A peaceful 3200-meter walk to reflect on your day and plan for tomorrow.",
    emoji: "🤔",
    timeStart: new Date().setHours(17, 0, 0, 0),
    timeEnd: new Date().setHours(21, 0, 0, 0),
    type: "distance-based",
    progress: 3200,
    maxValue: 3200,
    completedAt: new Date().setHours(20, 0, 0, 0),
  },
  {
    id: 15,
    timeOfDay: TimeOfDay.EVENING,
    title: "Moonlit Serenity",
    description:
      "End your day with a 20-minute serene walk under the moonlight.",
    emoji: "🌜",
    timeStart: new Date().setHours(20, 0, 0, 0),
    timeEnd: new Date().setHours(23, 0, 0, 0),
    type: "time-based",
    progress: 0,
    maxValue: 1200,
    completedAt: null,
  },
];

export default tasks;
