import { colors } from "../assets/styles/globalStyles";

const tasks = [
  {
    title: "Morning",
    color: colors.primary,
    data: [
      {
        title: "Sunrise Stroll",
        description:
          "Start your day with a calm 1-mile walk to greet the sunrise.",
        emoji: "🌅",
        timeStart: new Date().setHours(5, 0, 0, 0),
        timeEnd: new Date().setHours(8, 0, 0, 0),
        type: "distance-based",
        progress: 0.5,
        maxValue: 1.0,
        isCompleted: false,
      },
      {
        title: "Step Fresh",
        description: "Aim for 3,000 steps to energize your morning routine.",
        emoji: "👟",
        timeStart: new Date().setHours(6, 0, 0, 0),
        timeEnd: new Date().setHours(9, 0, 0, 0),
        type: "step-based",
        progress: 600,
        maxValue: 3000,
        isCompleted: false,
      },
      {
        title: "Park Explorer",
        description:
          "Explore a nearby park for 30 minutes, discovering a new route each time.",
        emoji: "🌳",
        timeStart: new Date().setHours(7, 0, 0, 0),
        timeEnd: new Date().setHours(10, 0, 0, 0),
        type: "time-based",
        progress: 30,
        maxValue: 30,
        isCompleted: true,
      },
      {
        title: "Morning Challenge",
        description: "Push for a quick 2-mile walk to boost your metabolism.",
        emoji: "🏃",
        timeStart: new Date().setHours(6, 0, 0, 0),
        timeEnd: new Date().setHours(11, 0, 0, 0),
        type: "distance-based",
        progress: 1,
        maxValue: 2,
        isCompleted: false,
      },
      {
        title: "Quiet Time Walk",
        description:
          "Take a 15-minute walk in silence, practicing mindfulness.",
        emoji: "🧘",
        timeStart: new Date().setHours(5, 0, 0, 0),
        timeEnd: new Date().setHours(8, 0, 0, 0),
        type: "time-based",
        progress: 15,
        maxValue: 15,
        isCompleted: true,
      },
    ],
  },
  {
    title: "Afternoon",
    color: colors.secondary,
    data: [
      {
        title: "Lunch Loop",
        description: "A brisk 1.5-mile walk post-lunch to aid digestion.",
        emoji: "🍽️",
        timeStart: new Date().setHours(11, 0, 0, 0),
        timeEnd: new Date().setHours(14, 0, 0, 0),
        type: "distance-based",
        progress: 0.75,
        maxValue: 1.5,
        isCompleted: false,
      },
      {
        title: "Step It Up",
        description:
          "Accumulate an additional 2,500 steps in your afternoon activities.",
        emoji: "👣",
        timeStart: new Date().setHours(12, 0, 0, 0),
        timeEnd: new Date().setHours(17, 0, 0, 0),
        type: "step-based",
        progress: 1250,
        maxValue: 2500,
        isCompleted: false,
      },
      {
        title: "Nature's Midday",
        description:
          "Spend 20 minutes walking in a natural setting, appreciating the daylight.",
        emoji: "🌞",
        timeStart: new Date().setHours(11, 0, 0, 0),
        timeEnd: new Date().setHours(15, 0, 0, 0),
        type: "time-based",
        progress: 20,
        maxValue: 20,
        isCompleted: true,
      },
      {
        title: "Urban Explorer",
        description:
          "Discover a new neighborhood or area in your city with a 2-mile walk.",
        emoji: "🏙️",
        timeStart: new Date().setHours(12, 0, 0, 0),
        timeEnd: new Date().setHours(17, 0, 0, 0),
        type: "distance-based",
        progress: 2,
        maxValue: 2,
        isCompleted: true,
      },
      {
        title: "Afternoon Reset",
        description:
          "A 10-minute walk to clear your mind and refocus for the rest of the day.",
        emoji: "🔄",
        timeStart: new Date().setHours(13, 0, 0, 0),
        timeEnd: new Date().setHours(16, 0, 0, 0),
        type: "time-based",
        progress: 5,
        maxValue: 10,
        isCompleted: false,
      },
    ],
  },
  {
    title: "Evening",
    color: colors.tertiary,
    data: [
      {
        title: "Sunset Wind Down",
        description: "A relaxing 1-mile walk to wind down as the sun sets.",
        emoji: "🌇",
        timeStart: new Date().setHours(17, 0, 0, 0),
        timeEnd: new Date().setHours(20, 0, 0, 0),
        type: "distance-based",
        progress: 0.5,
        maxValue: 1.0,
        isCompleted: false,
      },
      {
        title: "Evening Steps",
        description: "Gather the last 2,000 steps to meet your daily goal.",
        emoji: "🎯",
        timeStart: new Date().setHours(18, 0, 0, 0),
        timeEnd: new Date().setHours(21, 0, 0, 0),
        type: "step-based",
        progress: 2000,
        maxValue: 2000,
        isCompleted: true,
      },
      {
        title: "Night Sky Gazer",
        description:
          "15-minute walk under the night sky, stargazing and decompressing.",
        emoji: "🌌",
        timeStart: new Date().setHours(19, 0, 0, 0),
        timeEnd: new Date().setHours(22, 0, 0, 0),
        type: "time-based",
        progress: 7.5,
        maxValue: 15.0,
        isCompleted: false,
      },
      {
        title: "Reflective Walk",
        description:
          "A peaceful 2-mile walk to reflect on your day and plan for tomorrow.",
        emoji: "🤔",
        timeStart: new Date().setHours(17, 0, 0, 0),
        timeEnd: new Date().setHours(21, 0, 0, 0),
        type: "distance-based",
        progress: 2,
        maxValue: 2,
        isCompleted: true,
      },
      {
        title: "Moonlit Serenity",
        description:
          "End your day with a 20-minute serene walk under the moonlight.",
        emoji: "🌜",
        timeStart: new Date().setHours(20, 0, 0, 0),
        timeEnd: new Date().setHours(23, 0, 0, 0),
        type: "time-based",
        progress: 10,
        maxValue: 20,
        isCompleted: false,
      },
    ],
  },
];

export default tasks;
